[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PlantCabinetAutomation"
version = "1.0"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
            "adafruit-circuitpython-ahtx0" 
]